version: '3.9'
services:
  postgres-inscription:
    container_name: postgres-inscription
    image: postgres
    environment:
      POSTGRES_DB: gestion_inscription
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - ./postgres-inscription:/data/postgres
    ports:
      - "5431:5431"

  postgres-examen:
    container_name: postgres-examen
    image: postgres
    environment:
      POSTGRES_DB: gestion_examen
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - ./postgres-examen:/data/postgres
    ports:
      - "5433:5433"

  postgres-admission:
    container_name: postgres-admission
    image: postgres
    environment:
      POSTGRES_DB: gestion_admission
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - ./postgres-admission:/data/postgres
    ports:
      - "5434:5434"

  service-inscription:
    container_name: service-inscription
    image: inscription:latest
    build:
      context: ./service-inscription
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_URL=jdbc:postgresql://postgres-inscription:5431/gestion_inscription
    depends_on:
      - postgres-inscription

  service-examen:
    container_name: service-examen
    image: examen:latest
    build:
      context: ./service-examen
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_URL=jdbc:postgresql://postgres-examen:5433/gestion_examen
    depends_on:
      - postgres-examen

  service-admission:
    container_name: service-admission
    image: admission:latest
    build:
      context: ./service-admission
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_URL=jdbc:postgresql://postgres-admission:5434/gestion_admission
    depends_on:
      - postgres-admission

volumes:
  postgres-admission: {}
  postgres-examen: {}
  postgres-inscription: {}