version: '3.9'
services:
  mysql_inscriptions:
    container_name: mysql_inscriptions
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gestion_inscription
    volumes:
      - /d/my_volumes/mysql_inscriptions:/var/lib/mysql
    ports:
      - "3305:3306"


  mysql_examens:
    container_name: mysql_examens
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gestion_examen
    volumes:
      - /d/my_volumes/mysql_examens:/var/lib/mysql
    ports:
      - "3307:3306"

  mysql_admissions:
    container_name: mysql_admissions
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gestion_admission
    volumes:
      - /d/my_volumes/mysql_admissions:/var/lib/mysql
    ports:
      - "3308:3306"

  service_inscription:
    container_name: service_inscription
    image: inscription
    build:
      context: ./service-inscription
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - mysql_inscriptions
    networks:
        - my-network

  service_examen:
    container_name: service_examen
    image: examen
    build:
      context: ./service-examen
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - mysql_examens
    networks:
        - my-network

  service_admission:
    container_name: service_admission
    image: admission
    build:
      context: ./service-admission
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    depends_on:
      - mysql_admissions
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mysql_admissions: {}
  mysql_examens: {}
  mysql_inscriptions: {}
