version: '3.9'
services:
  mysql_inscription:
    container_name: mysql_inscription
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gestion_inscription
    volumes:
      - /d/volumes/mysql_inscription:/var/lib/mysql
    ports:
      - "3305:3306"

  mysql_examen:
    container_name: mysql_examen
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gestion_examen
    volumes:
      - /d/volumes/mysql_examen:/var/lib/mysql
    ports:
      - "3307:3306"

  mysql_admission:
    container_name: mysql_admission
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gestion_admission
    volumes:
      - /d/volumes/mysql_admission:/var/lib/mysql
    ports:
      - "3308:3306"

  service_inscription:
    container_name: service_inscription
    image: inscription
    build:
      context: ./service-inscription
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - mysql_inscription

  service_examen:
    container_name: service_examen
    image: examen
    build:
      context: ./service-examen
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - mysql_examen

  service_admission:
    container_name: service_admission
    image: admission
    build:
      context: ./service-admission
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    depends_on:
      - mysql_admission

volumes:
  mysql_admission: {}
  mysql_examen: {}
  mysql_inscription: {}
